//AUTH
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//PROFILE
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';

//SURVEYS
export const LOAD_SURVEY_SUCCESS = "LOAD_SURVEY_SUCCESS";
export const LOAD_SURVEY_FAILED = "LOAD_SURVEY_FAILED";

export const SURVEY_STARTED = "SURVEY_STARTED";
export const SURVEY_STOPPED = "SURVEY_STOPPED";
